### ISSUE TITLE
Wrong result with Masked image

### ISSUE THREAD

**Issue by kimsama** [keijiro/KinoObscurance#11]
It results unexpected result with an object which has masked shader. See the attached image. 

![ao_with_mask_error](https://cloud.githubusercontent.com/assets/564941/17430188/cc698966-5b2d-11e6-89ee-b842b06b3300.png)

**Comment by keijiro** [comment]
I suspect that shader ("Custom/Tapestry") has a problem. Is it possible to provide that shader to me for further inspection?

**Comment by kimsama** [comment]
Ok, I'll drop the email attached with that shader. 

[Edit] dropped the email to your gmail account, attached that shader.

**Comment by keijiro** [comment]
Thanks! I replied via email.
