### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by johnartune** [keijiro/KinoObscurance#13]
![hairbug_01](https://cloud.githubusercontent.com/assets/21257210/19798998/bf932c84-9d26-11e6-81b8-171a05312ce0.jpg)
This one have no use AO
![hairbug_02](https://cloud.githubusercontent.com/assets/21257210/19798999/bfa16b14-9d26-11e6-95e6-fdf33cdf53c1.jpg)
This one use KinoObscurance
![hairbug_03](https://cloud.githubusercontent.com/assets/21257210/19799000/bfa17492-9d26-11e6-8748-d3eab076fc70.jpg)
This one use Screen Space Ambient Obscurance

Thank you for your codes they are so much helpfull  to improve every frame effect beautfull and quickly. But steel have some problems.

My hari shader uses Dithered Alpha and Deferred Renderging and receve Light Attenuation, maybe because of the shadow or other something.

**Comment by keijiro** [comment]
Thanks for reporting! Would you mind providing me a minimum project that can reproduce this issue? I'd like to check the details.

**Comment by johnartune** [comment]
@keijiro Thanks your help, I'll letter to your Gmail, named (Hair KinoObscurance).
Thanks again.

**Comment by keijiro** [comment]
Thanks for providing the project! I looked into it, and found that the hair shader doesn't provide information that is needed to render depth normals texture.

It seems you're using ShaderForge. Please read the following issue report. This explains what's happening in your project.

https://shaderforge.userecho.com/topics/896-proper-depth-depth-normal-rendering/

I fixed the issue by adding few lines to the shader and tweaking the settings a little bit. I'll send you the fixed project later.

**Comment by johnartune** [comment]
Very kind of you, those days I have so many works to complet. Sorry for reply so later.
Yes the shader is use ShaderForge created. I have no idea how to remove the problem. Thank you for your help heartfeltly.
Good luck always with you.
PS: Waiting for your projects.

**Comment by keijiro** [comment]
@johnartune I've sent the project to you on 4th Nov. Check your inbox, or spam filter :)
