### ISSUE TITLE
Why would one use this over the SSAO built into the new post-processing suite?

### ISSUE THREAD

**Issue by andybak** [keijiro/KinoObscurance#16]
I believe that was also your work (or partly your work?). How does this repo differ? I'm especially interested in using it for VR - I have found any SSAO effect so far that have been very usable in VR.

**Comment by keijiro** [comment]
They're almost identical. There is no legitimate reason to use this version any more. I'm still using this though.

**Comment by andybak** [comment]
Probably worth adding a line to the readme to that effect.
