### ISSUE TITLE
Question . Unity 2019 ?

### ISSUE THREAD

**Issue by drugin** [keijiro/KinoObscurance#21]
Good day. Will there be support for version 2019? in this version is incorrectly obscured. visible through the map other objects with your decision. You will need to update or go to another solution. ??

**Comment by keijiro** [comment]
I strongly recommend using Post Processing Stack instead. It's better and faster than this.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
